refactor: simplify CI workflow branch configuration and clean up comments

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -2,11 +2,9 @@ name: CI - ft_transcendence
 
 on:
   push:
-    branches:
-      ["master", "dev"]
+    branches: ["master", "dev"]
   pull_request:
-    branches:
-      ["master", "dev"]
+    branches: ["master", "dev"]
 
 jobs:
   check-repository:
@@ -16,20 +14,8 @@ jobs:
       - name: Check repository
         run: |
           if [ -f .env ]; then echo " Error: .env file detected in repo!"; exit 1; fi
-            if [ -d node_modules ]; then echo " Error: node_modules detected in repo!"; exit 1; fi
-            echo " Repository is clean."
-
-jobs:
-  # build-and-test:
-    # runs-on: ubuntu-latest
-    # steps:
-    #   - name: build-test
-    #   - uses: actions/checkout@v4
-
-
-# On check pour nodes_modules car pollue l'historique git et rend le clonage plus long
-
-# Si le depot est propre on essaye de build le projet
+          if [ -d node_modules ]; then echo " Error: node_modules detected in repo!"; exit 1; fi
+          echo " Repository is clean."
 
   build-test:
     needs: check-repository
